AEMAssessment/Controllers/PlatformWellController.cs
using AEMAssessment.Models;
using AEMAssessment.Storage;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net;
using System.Net.Http.Headers;
using Platform = AEMAssessment.Models.Platform;

namespace AEMAssessment.Controllers
{
    public class PlatformWellController : Controller
    {
        protected readonly IContextBuilder ContextBuilder;
        private readonly LocalDbContext context;
        public static string baseUrl = "http://test-demo.aemenersol.com/api/PlatformWell/GetPlatformWellActual";

        public PlatformWellController(LocalDbContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            var platformWell = await GetPlatformWellActual();
            return View(platformWell);
        }

        [HttpGet]
        //public async Task<List<Platform>> GetPlatformWell()
        //{
        //    var platformList = await context.Platform.ToListAsync();
        //    return platformList;
        //}

        [HttpGet]
        public async Task<List<PlatformWell>> GetPlatformWellActual()
        {
            List<Platform> listPlatform = new List<Platform>();
            List<Well> listWell = new List<Well>();
            List<PlatformWell> res = new List<PlatformWell>();

            var accessToken = HttpContext.Session.GetString("JWToken");
            accessToken = accessToken?.Replace('"'.ToString(), string.Empty);
            var url = baseUrl;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonStr = await client.GetStringAsync(url);        

            try
            {
                res = JsonConvert.DeserializeObject<List<PlatformWell>>(jsonStr);
            }
            catch (Exception)
            {
                foreach (var item in res)
                {
                    Platform platform = new Platform();
                }
                return res;
            }

            
            //if (res.Count > 0)
            //{
            //    await context.PlatformWell.AddRange(res);
            //}
            

            var platformList = GetPlatformData(res);
            var wellList = GetWellData(res);
            var platformListDb = await GetPlatformDb();
            var wellListDb = await GetWellDb();

            if (platformListDb.Count <= 0 && platformList.Count > 0)
            {
                context.Platform.AddRange(platformList);
                await context.SaveChangesAsync();
            }
            else
            {
                foreach (var item in platformListDb.Where(first => platformList.Any(second => second.Id == first.Id)))
                {
                    item.UpdatedAt = DateTime.Now;
                    await context.SaveChangesAsync();
                }
            }

            if (wellListDb.Count <= 0 && wellList.Count > 0)
            {
                context.Well.AddRange(wellList);
                await context.SaveChangesAsync();
            }
            else
            {
                foreach (var item in wellListDb.Where(first => wellList.Any(second => second.Id == first.Id)))
                {
                    item.UpdatedAt = DateTime.Now;
                    await context.SaveChangesAsync();
                }
            }
            
            return res;
        }

        public List<Platform> GetPlatformData(List<PlatformWell> platformWellList)
        {
            var result = new List<Platform>();

            foreach (var item in platformWellList)
            {
                Platform platform = new Platform();
                platform.Id = item.Id;
                platform.UniqueName = item.UniqueName;
                platform.Latitude = item.Latitude;
                platform.Longitude = item.Longitude;
                platform.CreatedAt = item.CreatedAt;
                platform.UpdatedAt = item.UpdatedAt;

                result.Add(platform);
            }
            return result;
        }

        public List<Well> GetWellData(List<PlatformWell> platformWellList)
        {
            var result = new List<Well>();     

            foreach (var item in platformWellList)
            {
                List<Well> wellList = item.Well;

                foreach (var well in wellList)
                {
                    Well wellObj = new Well();
                    wellObj.Id = well.Id;
                    wellObj.PlatformId = well.PlatformId;
                    wellObj.UniqueName = well.UniqueName;
                    wellObj.Latitude = well.Latitude;
                    wellObj.Longitude = well.Longitude;
                    wellObj.CreatedAt = well.CreatedAt;
                    wellObj.UpdatedAt = well.UpdatedAt;

                    result.Add(wellObj);
                }
            }
            return result;
        }

        [HttpGet]
        public async Task<List<Platform>> GetPlatformDb()
        {
            var platformListDb = await context.Platform.ToListAsync();

            return platformListDb;
        }

        [HttpGet]
        public async Task<List<Well>> GetWellDb()
        {
            var wellListDb = await context.Well.ToListAsync();

            return wellListDb;
        }
    }
}

AEMAssessment/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AEMAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AEMAssessment.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AEMAssessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AEMAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AEMAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AEMAssessment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AEMAssessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlatformWell" asp-action="GetPlatformWellActual">Save Platform Well Data</a>
                        </li>
                    </ul>
                    <a class="btn btn-sm btn-danger" asp-area="" asp-controller="Home" asp-action="LogOff" style="float:right;">LogOff</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AEMAssessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>